version: '2'

services:

  data_container:
    image: symball/data_container
    # image: busybox
    stdin_open: true
    tty: true
    links:
      - mongo
    volumes:
      - ./site/build:/var/www/html

  nginx:
    build: docker/nginx
    ports:
      - 8086:8000
    volumes_from:
     - data_container
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm

  fpm:
    image: symball/php
    links:
      - mongo
    volumes_from:
     - data_container

  mongo:
    image: mongo
    volumes:
      - ./docker/data/mongo:/var/lib/mongo
